import type { Metadata } from "next";
import "@/app/globals.css";
import { TopBar } from "@/components/layout/top-bar";

export const metadata: Metadata = {
  title: "Bexalite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body>
        <TopBar />
        <div className="flex h-full">
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
