import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/dist/client/link";
import { TopBar } from "@/components/layout/top-bar";
import { SideBar } from "@/components/layout/side-bar";

export const metadata: Metadata = {
  title: "Bexalite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
